apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: xxrq1araw-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: xxrq1araw-python 
  name: xxrq1araw-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: xxrq1araw-python 
